name: Erc20
description: ERC-20 PoC for IOTA Smart Contracts
structs: {}
typedefs:
  AllowancesForAgent: '[AgentID]Int64'
state:
  allAllowances=a: '[AgentID]AllowancesForAgent'
  balances=b: '[AgentID]Int64 // balances per account'
  supply=s: Int64 // total supply of the token
funcs:
  approve:
    params:
      amount=am: Int64 // allowance value for delegated account
      delegation=d: AgentID // delegated account
  init:
    params:
      creator=c: AgentID // creator/owner of the initial supply
      supply=s: Int64 // initial token supply
  transfer:
    params:
      account=ac: AgentID // target account
      amount=am: Int64 // amount of tokens to transfer
  transferFrom:
    params:
      account=ac: AgentID // sender account
      amount=am: Int64 // amount of tokens to transfer
      recipient=r: AgentID // recipient account
views:
  allowance:
    params:
      account=ac: AgentID // sender account
      delegation=d: AgentID // delegated account
    results:
      amount=am: Int64
  balanceOf:
    params:
      account=ac: AgentID // sender account
    results:
      amount=am: Int64
  totalSupply:
    results:
      supply=s: Int64
